/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTeamsRouteImport } from './routes/_app/teams'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRecognitionRouteImport } from './routes/_app/recognition'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppGalleryRouteImport } from './routes/_app/gallery'
import { Route as AppDiscussionsRouteImport } from './routes/_app/discussions'
import { Route as AppDirectoryRouteImport } from './routes/_app/directory'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAnnouncementsRouteImport } from './routes/_app/announcements'
import { Route as AppAdminRouteImport } from './routes/_app/admin'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecognitionRoute = AppRecognitionRouteImport.update({
  id: '/recognition',
  path: '/recognition',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryRoute = AppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscussionsRoute = AppDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryRoute = AppDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/calendar': typeof AppCalendarRoute
  '/directory': typeof AppDirectoryRoute
  '/discussions': typeof AppDiscussionsRoute
  '/gallery': typeof AppGalleryRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/recognition': typeof AppRecognitionRoute
  '/settings': typeof AppSettingsRoute
  '/teams': typeof AppTeamsRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AppAdminRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/calendar': typeof AppCalendarRoute
  '/directory': typeof AppDirectoryRoute
  '/discussions': typeof AppDiscussionsRoute
  '/gallery': typeof AppGalleryRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/recognition': typeof AppRecognitionRoute
  '/settings': typeof AppSettingsRoute
  '/teams': typeof AppTeamsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/directory': typeof AppDirectoryRoute
  '/_app/discussions': typeof AppDiscussionsRoute
  '/_app/gallery': typeof AppGalleryRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/recognition': typeof AppRecognitionRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/teams': typeof AppTeamsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/calendar'
    | '/directory'
    | '/discussions'
    | '/gallery'
    | '/knowledge'
    | '/leaderboard'
    | '/recognition'
    | '/settings'
    | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/announcements'
    | '/calendar'
    | '/directory'
    | '/discussions'
    | '/gallery'
    | '/knowledge'
    | '/leaderboard'
    | '/recognition'
    | '/settings'
    | '/teams'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/admin'
    | '/_app/announcements'
    | '/_app/calendar'
    | '/_app/directory'
    | '/_app/discussions'
    | '/_app/gallery'
    | '/_app/knowledge'
    | '/_app/leaderboard'
    | '/_app/recognition'
    | '/_app/settings'
    | '/_app/teams'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recognition': {
      id: '/_app/recognition'
      path: '/recognition'
      fullPath: '/recognition'
      preLoaderRoute: typeof AppRecognitionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gallery': {
      id: '/_app/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AppGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discussions': {
      id: '/_app/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof AppDiscussionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/directory': {
      id: '/_app/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AppDirectoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDirectoryRoute: typeof AppDirectoryRoute
  AppDiscussionsRoute: typeof AppDiscussionsRoute
  AppGalleryRoute: typeof AppGalleryRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppRecognitionRoute: typeof AppRecognitionRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDirectoryRoute: AppDirectoryRoute,
  AppDiscussionsRoute: AppDiscussionsRoute,
  AppGalleryRoute: AppGalleryRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppRecognitionRoute: AppRecognitionRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
